// Direction « Monarchie en pyjama » : des crises du quotidien élevées au rang de décrets royaux, avec humour et vraies tensions de ressources.
import type { GameEvent } from "./types";

const ART = {
  layer: { glyph: "≈", color: "#152542", background: "#F7C948" },
  plush: { glyph: "✦", color: "#152542", background: "#B9A8E6" },
  bottle: { glyph: "⌁", color: "#152542", background: "#8CB9DC" },
  music: { glyph: "♪", color: "#152542", background: "#B9A8E6" },
  moon: { glyph: "◔", color: "#152542", background: "#F7C948" },
  alert: { glyph: "!", color: "#FFF8E7", background: "#D8544B" },
  stock: { glyph: "□", color: "#152542", background: "#8CB9DC" },
  crown: { glyph: "♛", color: "#152542", background: "#F7C948" },
  water: { glyph: "◇", color: "#152542", background: "#8CB9DC" },
  star: { glyph: "✧", color: "#152542", background: "#E9D9F7" },
} as const;

export const EVENTS: GameEvent[] = [
  {
    id: "cacapocalypse",
    title: "Cacapocalypse nocturne",
    story: "À 3 h 12, la couche royale déborde dangereusement. Le souverain gazouille, inconscient de la crise.",
    art: ART.layer,
    left: { label: "Faire semblant de dormir", consequence: "Vous gagnez quelques minutes, mais le royaume s’en souviendra.", effects: { sleep: 10, clean: -28, stress: 18 } },
    right: { label: "Intervenir en ninja", consequence: "Opération couche propre réussie. Votre oreiller vous manque déjà.", effects: { sleep: -10, clean: 26, stress: -7, stock: -16 } },
  },
  {
    id: "doudou",
    title: "Rituel du doudou",
    story: "Le doudou a disparu. Sans lui, le petit monarque menace de renverser le berceau.",
    art: ART.plush,
    left: { label: "Fouiller chaque tiroir", consequence: "Le doudou est retrouvé sous la commode. Vous, un peu moins.", effects: { sleep: -9, stress: 8, stock: 4 } },
    right: { label: "Promouvoir une chaussette", consequence: "La chaussette devient doudou intérimaire. La cour proteste, puis hésite.", effects: { sleep: -3, clean: -7, stress: 11, stock: 3 } },
  },
  {
    id: "biberon",
    title: "Biberon à l’aube",
    story: "Un petit poing frappe le matelas comme une cloche. Le biberon est exigé immédiatement.",
    art: ART.bottle,
    left: { label: "Réchauffer un biberon", consequence: "Le souverain est repu. La réserve de la cour, elle, rétrécit.", effects: { sleep: 12, stress: -10, stock: -18 } },
    right: { label: "Négocier cinq minutes", consequence: "La diplomatie échoue sur un cri d’une grande précision.", effects: { sleep: -12, stress: 17, stock: 2 } },
  },
  {
    id: "chat",
    title: "Le chat chante l’hymne",
    story: "Le chat décide que le couloir est une salle de concert. Bébé ouvre un œil très officiel.",
    art: ART.music,
    left: { label: "Exiler le chat avec douceur", consequence: "Le récital cesse. Le chat inscrit votre nom dans ses archives.", effects: { sleep: 8, stress: 4 } },
    right: { label: "Laisser l’artiste s’exprimer", consequence: "Un duo miaou-pleur se forme. Personne n’applaudit.", effects: { sleep: -15, stress: 13 } },
  },
  {
    id: "bavoir",
    title: "Révolte du bavoir",
    story: "Une vague de compote atteint le pyjama, le drap et, par miracle, le plafond.",
    art: ART.layer,
    left: { label: "Changer tout le royaume", consequence: "La lessive s’agrandit, mais la dignité revient dans le berceau.", effects: { clean: 23, sleep: -7, stock: -8, stress: 2 } },
    right: { label: "Déplacer le bavoir et prier", consequence: "Le plan tient exactement neuf secondes.", effects: { clean: -20, sleep: 5, stress: 12 } },
  },
  {
    id: "comete",
    title: "Le mobile devient comète",
    story: "Le mobile tourne si vite qu’il fascine le bébé. Le sommeil vient de quitter l’orbite.",
    art: ART.star,
    left: { label: "Retirer le mobile", consequence: "Le ciel redevient calme. Un petit drame diplomatique éclate.", effects: { sleep: 9, stress: 5 } },
    right: { label: "Observer l’astronomie", consequence: "C’est instructif, et totalement contraire au plan de sommeil.", effects: { sleep: -14, stress: 9 } },
  },
  {
    id: "porte",
    title: "Porte qui grince",
    story: "Un grincement minuscule ressemble soudain à un dragon qui se réveille dans le couloir.",
    art: ART.alert,
    left: { label: "Huiler la porte maintenant", consequence: "Le dragon se tait. Vous perdez une précieuse minute de repos.", effects: { sleep: -5, stress: -6, stock: -4 } },
    right: { label: "Marcher sur la pointe des pieds", consequence: "Le troisième pas transforme le grincement en concert.", effects: { sleep: -11, stress: 12 } },
  },
  {
    id: "royal-decret",
    title: "Décret de câlins",
    story: "Le bébé exige d’être porté, immédiatement et par décret à durée indéterminée.",
    art: ART.crown,
    left: { label: "Porter le souverain", consequence: "Le calme revient contre votre épaule. Vos bras déposent une réclamation.", effects: { sleep: 13, stress: -7 } },
    right: { label: "Chanter depuis le trône", consequence: "Votre berceuse surprend. Le bébé juge la performance sans pitié.", effects: { sleep: -6, stress: 8 } },
  },
  {
    id: "pajama-party",
    title: "Le pyjama est introuvable",
    story: "Le pyjama propre a disparu, vraisemblablement dans le territoire interdit de la corbeille à linge.",
    art: ART.plush,
    left: { label: "Partir en expédition lessive", consequence: "Vous retrouvez le pyjama. Quelqu’un a déclaré la guerre à vos chaussettes.", effects: { clean: 17, sleep: -8, stress: 4 } },
    right: { label: "Improviser une tenue royale", consequence: "Une cape en serviette fait sensation, puis absorbe trop peu.", effects: { clean: -10, stress: -3, stock: 2 } },
  },
  {
    id: "tasse",
    title: "Le verre d’eau interdit",
    story: "Vous entendez le bruit inquiétant d’un gobelet qui roule vers le tapis.",
    art: ART.water,
    left: { label: "Sauver le tapis", consequence: "Le tapis survit. Votre réveil aussi, de justesse.", effects: { clean: 15, sleep: -7, stress: 3 } },
    right: { label: "Sauver votre dos", consequence: "Le tapis reçoit un baptême officiel à l’eau tiède.", effects: { clean: -16, sleep: 4, stress: 8 } },
  },
  {
    id: "micro-reveil",
    title: "Fausse accalmie",
    story: "Tout est silencieux. Trop silencieux. Est-ce enfin le sommeil ou un piège stratégique ?",
    art: ART.moon,
    left: { label: "Vous allonger aussi", consequence: "Trois respirations de paix absolue. Un record de la cour.", effects: { sleep: 15, stress: -13 } },
    right: { label: "Vérifier le berceau", consequence: "Le sol grince. Le souverain ouvre un œil accusateur.", effects: { sleep: -8, stress: 7 } },
  },
  {
    id: "placard-secret",
    title: "Le placard secret",
    story: "Derrière une pile de serviettes, vous apercevez un paquet oublié. Trésor ou hallucination de fatigue ?",
    art: ART.stock,
    left: { label: "Inventorier le trésor", consequence: "Couches, lingettes, compotes : la cour retrouve des réserves inespérées.", effects: { stock: 24, sleep: -8, stress: -3 } },
    right: { label: "Ne surtout rien déranger", consequence: "Le trésor attendra. Votre demi-sommeil, lui, remercie cette sagesse.", effects: { sleep: 8, stress: -5 } },
  },
  {
    id: "veilleuse",
    title: "La veilleuse vacille",
    story: "La lumière sacrée clignote. Le bébé fixe le plafond comme si le royaume allait disparaître.",
    art: ART.star,
    left: { label: "Changer les piles", consequence: "La lune artificielle renaît. Les piles de secours, un peu moins.", effects: { sleep: 8, stress: -8, stock: -7 } },
    right: { label: "Faire confiance à la lune", consequence: "Ambiance poétique. Efficacité diplomatique discutable.", effects: { sleep: -8, stress: 7 } },
  },
  {
    id: "rot-royal",
    title: "Audience après biberon",
    story: "Le repas est terminé mais l’audience ne l’est pas. Le souverain refuse catégoriquement de se rendormir.",
    art: ART.bottle,
    left: { label: "Prolonger l’audience", consequence: "Quelques pas dans le couloir et le calme revient progressivement.", effects: { sleep: 10, stress: -4 } },
    right: { label: "Rendre le trône au berceau", consequence: "Décision administrative rapide. Recours immédiat du principal intéressé.", effects: { sleep: -10, stress: 12 } },
  },
  {
    id: "livraison-couches",
    title: "Convoi de couches retrouvé",
    story: "Un carton de ravitaillement oublié attend dans l’entrée. Il faut seulement traverser le parquet maudit.",
    art: ART.stock,
    minNight: 2,
    left: { label: "Rapatrier le convoi", consequence: "Mission accomplie. Le stock respire, le parquet a tenté deux trahisons.", effects: { stock: 28, sleep: -10, stress: 5 } },
    right: { label: "Attendre le matin", consequence: "Le carton reste en exil et vous conservez quelques minutes de silence.", effects: { sleep: 9, stock: -3 } },
  },
  {
    id: "tetine-sous-lit",
    title: "La tétine sous le lit",
    story: "La tétine roule dans l’ombre interdite. On entend déjà le début d’une crise constitutionnelle.",
    art: ART.plush,
    minNight: 2,
    left: { label: "Ramper sous le lit", consequence: "Victoire tactique. Votre dos annonce qu’il quittera le gouvernement demain.", effects: { sleep: 11, stress: -6, clean: -5 } },
    right: { label: "Sortir la tétine de secours", consequence: "Le plan B fonctionne, mais les réserves perdent une cartouche précieuse.", effects: { sleep: 7, stress: -4, stock: -9 } },
  },
  {
    id: "babyphone",
    title: "Le babyphone prophétise",
    story: "Un souffle, un grésillement, peut-être un cri. Le babyphone transforme chaque bruit en affaire d’État.",
    art: ART.alert,
    minNight: 2,
    left: { label: "Aller vérifier", consequence: "Fausse alerte. Vous avez réveillé une latte du parquet, pas le bébé.", effects: { sleep: -7, stress: -4 } },
    right: { label: "Faire confiance au silence", consequence: "Bonne intuition. Votre cerveau refuse néanmoins de désactiver l’alarme interne.", effects: { sleep: 8, stress: 6 } },
  },
  {
    id: "machine-laver",
    title: "La machine réclame justice",
    story: "Le panier de linge déborde. Une lessive maintenant pourrait sauver la propreté de demain, mais pas votre nuit.",
    art: ART.water,
    minNight: 2,
    left: { label: "Lancer une lessive discrète", consequence: "Le linge tourne. La machine découvre soudain une passion pour l’essorage théâtral.", effects: { clean: 22, sleep: -12, stress: 5, stock: -4 } },
    right: { label: "Déclarer demain compétent", consequence: "Le panier devient officiellement le problème du gouvernement suivant.", effects: { sleep: 8, clean: -9, stress: -3 } },
  },
  {
    id: "chaussette-perdue",
    title: "La chaussette dissidente",
    story: "Une chaussette minuscule a disparu entre le lit et le berceau. Personne ne sait pourquoi cela semble soudain essentiel.",
    art: ART.plush,
    minNight: 2,
    left: { label: "Mener l’enquête", consequence: "La fugitive est retrouvée. La cour gagne une chaussette et perd huit minutes.", effects: { clean: 8, sleep: -8, stress: 3 } },
    right: { label: "Classer l’affaire sans suite", consequence: "Décision raisonnable. Votre cerveau ouvre tout de même un dossier permanent.", effects: { sleep: 5, stress: 5 } },
  },
  {
    id: "reserve-compote",
    title: "Réserve de compotes",
    story: "Vous découvrez un lot de compotes derrière les casseroles. La date est bonne, votre humeur aussi soudainement.",
    art: ART.stock,
    minNight: 2,
    left: { label: "Réorganiser le stock", consequence: "Les réserves remontent et, miracle, vous savez enfin où sont les cuillères.", effects: { stock: 20, clean: 5, sleep: -9, stress: -5 } },
    right: { label: "Refermer doucement", consequence: "Le futur vous remerciera peut-être. Le présent choisit le sommeil.", effects: { sleep: 8, stress: -3 } },
  },
  {
    id: "berceuse-en-boucle",
    title: "Berceuse en boucle",
    story: "La même berceuse joue pour la quatorzième fois. Bébé semble apaisé. Votre esprit commence à négocier sa sortie.",
    art: ART.music,
    minNight: 2,
    left: { label: "Laisser tourner encore", consequence: "Le souverain s’apaise. La chanson s’installe définitivement dans votre cortex.", effects: { sleep: 12, stress: 8 } },
    right: { label: "Couper au refrain", consequence: "Le silence est magnifique pendant exactement quatre secondes.", effects: { sleep: -8, stress: -4 } },
  },
  {
    id: "biberon-renverse",
    title: "Le biberon se renverse",
    story: "Une flaque progresse sur la table de nuit avec l’ambition territoriale d’un petit empire.",
    art: ART.bottle,
    minNight: 2,
    left: { label: "Nettoyer immédiatement", consequence: "La table est sauvée, la ration est perdue et le rouleau d’essuie-tout prend cher.", effects: { clean: 18, stock: -13, sleep: -6, stress: 4 } },
    right: { label: "Contenir avec une serviette", consequence: "La frontière tient. La serviette est promue digue nationale.", effects: { clean: -8, stock: -3, stress: -3 } },
  },
  {
    id: "orage",
    title: "Tonnerre au-dessus du palais",
    story: "Un coup de tonnerre secoue les vitres. Le bébé se redresse, outré que le ciel fasse autant de bruit sans autorisation.",
    art: ART.alert,
    minNight: 3,
    left: { label: "Rassurer dans les bras", consequence: "La tempête continue dehors, mais la petite cour se calme contre vous.", effects: { sleep: 10, stress: -8 } },
    right: { label: "Attendre que ça passe", consequence: "Le ciel insiste. Le souverain aussi.", effects: { sleep: -15, stress: 13 } },
  },
  {
    id: "stock-fantome",
    title: "Le paquet presque vide",
    story: "Le paquet de couches paraît plein. En réalité, trois couches et beaucoup d’air occupent le royaume.",
    art: ART.stock,
    minNight: 3,
    left: { label: "Faire les fonds de placard", consequence: "Vous réunissez un petit trésor de secours au prix d’une expédition épuisante.", effects: { stock: 18, sleep: -12, stress: 6 } },
    right: { label: "Économiser chaque unité", consequence: "La réserve tient mieux, la propreté devient une affaire de précision militaire.", effects: { stock: 6, clean: -11, stress: 5 } },
  },
  {
    id: "festival-peluches",
    title: "Conseil des peluches",
    story: "Trois peluches tombent du lit les unes après les autres. Le bébé réclame leur retour selon un protocole très précis.",
    art: ART.plush,
    minNight: 3,
    left: { label: "Réinstaller toute la cour", consequence: "Chaque peluche retrouve son rang. Vous ne savez plus quel est le vôtre.", effects: { sleep: 9, stress: 3 } },
    right: { label: "Limiter le conseil à une peluche", consequence: "Réforme courageuse. L’opposition est immédiate et sonore.", effects: { sleep: -10, stress: 9 } },
  },
  {
    id: "reveil-parent",
    title: "Votre réveil sonne trop tôt",
    story: "Le réveil se déclenche alors que la nuit n’est pas officiellement terminée. Une erreur administrative aux conséquences graves.",
    art: ART.alert,
    minNight: 3,
    left: { label: "Le couper instantanément", consequence: "Réflexe parfait. Vous restez éveillé, mais le bébé non.", effects: { sleep: 6, stress: 5 } },
    right: { label: "Chercher le téléphone à tâtons", consequence: "Le réveil gagne deux rappels. Le bébé gagne un public.", effects: { sleep: -14, stress: 12 } },
  },
  {
    id: "grand-rangement",
    title: "Le sol devient territoire hostile",
    story: "Biberon, lange, livre, chaussette : le passage jusqu’au lit ressemble à une carte d’aventure mal conçue.",
    art: ART.layer,
    minNight: 3,
    left: { label: "Ranger le passage", consequence: "Le trajet redevient praticable. Votre énergie, beaucoup moins.", effects: { clean: 21, sleep: -11, stress: -4 } },
    right: { label: "Mémoriser les obstacles", consequence: "Vous développez une cartographie mentale admirable et totalement inutile demain.", effects: { clean: -12, sleep: 5, stress: 6 } },
  },
  {
    id: "derniere-dose",
    title: "La dernière dose",
    story: "Il reste juste assez de lait pour un biberon confortable. L’aube est proche, mais pas assez proche.",
    art: ART.bottle,
    minNight: 3,
    left: { label: "Servir la dose complète", consequence: "Le souverain se rendort. Les réserves passent officiellement en mode héroïque.", effects: { sleep: 15, stress: -8, stock: -20 } },
    right: { label: "Préserver la réserve", consequence: "Gestion prudente. Le principal actionnaire exprime son désaccord à plein volume.", effects: { sleep: -13, stress: 14, stock: 5 } },
  },
  {
    id: "fenetre-aube",
    title: "Une ligne rose à l’horizon",
    story: "La lumière commence à filtrer sous le rideau. Le royaume peut presque sentir l’aube, ce qui est très différent de l’atteindre.",
    art: ART.moon,
    minNight: 3,
    left: { label: "Fermer les rideaux", consequence: "La chambre redevient nuit. Vous gagnez un peu de calme et une étrange victoire morale.", effects: { sleep: 11, stress: -5 } },
    right: { label: "Accepter l’arrivée du jour", consequence: "Le matin entre avant l’heure. Le souverain prend cela pour une invitation.", effects: { sleep: -12, stress: 8 } },
  },
  {
    id: "aube",
    title: "L’aube approche",
    story: "Une lueur glisse sous le rideau. Le royaume n’a plus que quelques décisions à tenir.",
    art: ART.crown,
    minNight: 3,
    left: { label: "Préparer le petit-déjeuner", consequence: "La journée est presque prête. Vos réserves ne le sont plus vraiment.", effects: { stock: -13, stress: -5, sleep: 4 } },
    right: { label: "Retarder le monde extérieur", consequence: "Le temps ne s’arrête pas, mais l’intention était noble.", effects: { sleep: -5, stress: 9 } },
  },
];
